classdef ACclass
    %ACCLASS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        Name
        
        MTOM                                                            % Maximum TakeOff Mass [kg]
        MTO                                                             % Max. TO Weight
        MLND                                                            % Max LND Weight
        MZF                                                             % Max Zero Fuel [Kg]
        
        Sw
        bw
        cref
        ARw
        
        I           % Inertia Tensor [Kg m^2]
        CG          % Center of Mass in constructive frame [m]
        
        CD0
        K
        CLcdm       % cl@cdMIN [1/DEG]
        CLmax
        CLa         % CL vs alpha linear slope [1/deg]
        CL0
        CMa         % CM vs alpha slope. Moments are referred to the center of mass [1/deg] 
        CM0
        CLad        % CL vs alpha dor derivative [rad^-1 s^-1]   
        CMad
        CLq
        CMq
        CMM         % dCM/dM at given Alpha
        CLde
        CMde
        
        Cyb
        Cnb
        Clb
        Clp
        Cnp
        Clr
        Cnr
        
        CL
        CM
        polar
        
        Kp
        Kb
        Ki
        lat % 2zita*wn wn^2
        Klat
        
        EnPs
        Neng
        RPM
        Pmax    % Max Power @S/L
        Dprop
        aTS      % Thust Coefficients
        aTC
    end
    
    methods
        function obj = ACclass(file_name)
            %ACCLASS Construct an instance of this class
            %   Detailed explanation goes here
            %   INPUT
            %   - data_name: name of .mat file containing the aerodynamic
            %               database
            %   - MSs: vector containing all the required masses
            %               [MTOM,MZF]
            %   - Wng: vector containing [Sw,bw] for the wing
            %obj.Property1 = inputArg1 + inputArg2;
            
            % Masses
            [obj,data_name,gain_file,inert_file,prop_file] = ...
                obj.read_input(file_name);
            obj.ARw = obj.bw^2/obj.Sw;
            %% Propeller Data
            try
            load(prop_file,'prop_data_simp','prop_data_comp'); % prop_data = [k0,kv,Jinf,Jmax] Jinf,Jmax are the bounds of the advance ratio where the regression is valid
            obj.aTS.cfs = prop_data_simp(1:2);
            obj.aTS.bds = prop_data_simp(3:4);
            obj.aTC.cfs = prop_data_comp;
            catch ERR
                 warning('Could not load Engine Data')
                obj.aTS.cfs = nan;
                obj.aTS.bds = nan;
                obj.aTC.cfs = nan;
            end
            %% Inertia
            try
            load(inert_file,'Inertia_Tensor','CG')
            obj.I = Inertia_Tensor;
            obj.CG = CG;
            catch ERR
                warning('Could not load Inertia Data')
                obj.I = nan(3);
                obj.CG = nan;
            end
            %% Definition of Interpolating Functions
            % aero_synt and aero_synt_M are generated by the
            % BuildAeroModel.m file.
            % aero_synt = [
            % M,Re,CD0,K,CL@CDmin,CLmax,alphamax,CLa,CL0,CMa,CM0,x,CLda,x,CMda,x,
            %         Clde,x,CMde,CLq,CMq ]
            % aero_synt_M = [ alpha, dCM/dM ]
            % aero_synt_C = 
            %       [ M,Re,CMe,CM0e,CLe,CL0e,min( deltaE ),max( deltaE ) ]
            try
            load(data_name,'aero_synt','aero_synt_M','aero_synt_C')           % TODO: includere anche condizioni T/O e Land
            obj.CD0 = scatteredInterpolant(aero_synt(:,1),...           % CD0 interpolation
                aero_synt(:,2),aero_synt(:,3) );
            obj.K = scatteredInterpolant(aero_synt(:,1),...             % CL@CDmin interpolation
                aero_synt(:,2),aero_synt(:,4) );
            obj.CLcdm = scatteredInterpolant(aero_synt(:,1),...       % CL@CDmin interpolation
                aero_synt(:,2),aero_synt(:,5) );
            obj.CLmax = scatteredInterpolant(aero_synt(:,1),...         % CLmax interpolation
                aero_synt(:,2),aero_synt(:,6) );            
            obj.CLa = scatteredInterpolant(aero_synt(:,1),...         % CLa interpolation
                aero_synt(:,2),aero_synt(:,8) );
            obj.CL0 = scatteredInterpolant(aero_synt(:,1),...         % CL0 interpolation
                aero_synt(:,2),aero_synt(:,9) );
            obj.CMa = scatteredInterpolant(aero_synt(:,1),...         % CLa interpolation
                aero_synt(:,2),aero_synt(:,10) );
            obj.CM0 = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,11) );

            obj.CLq = griddedInterpolant(unique(aero_synt(:,1)),...         % CLq interpolation
                unique(aero_synt(:,16)),'linear','nearest' );
            obj.CMq = griddedInterpolant(unique(aero_synt(:,1)),...         % CMq interpolation
                unique(aero_synt(:,17)),'linear','nearest' );
             % [M,h,alpha,Cyb,Cnb,Clb,Clp,Cnp,Clr,Cnr]
            obj.Cyb = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,18) );
            obj.Cnb = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,19) );
            
            obj.Clb = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,20) );
            obj.Clp = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,21) );
            obj.Cnp = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,22) );
            obj.Clr = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,23) );
            obj.Cnr = scatteredInterpolant(aero_synt(:,1),...         % CM0 interpolation
                aero_synt(:,2),aero_synt(:,24) );
            
            obj.CL = @CLvsAoA;
            obj.CM = @(M,Re,alpha) obj.CMa(M,Re)*alpha + obj.CM0(M,Re);
            % dCL/dad
            CH1 = scatteredInterpolant(aero_synt(:,1),...        % CLad interpolation
                aero_synt(:,2),aero_synt(:,12) );
            CH2 = scatteredInterpolant(aero_synt(:,1),...        % CLad interpolation
                aero_synt(:,2),aero_synt(:,13) );
            obj.CLad = @(M,Re,alpha) CH1(M,Re)*alpha + CH2(M,Re);
            % dCM/dad
            CH3 = scatteredInterpolant(aero_synt(:,1),...        % CLad interpolation
                aero_synt(:,2),aero_synt(:,14) );
            CH4 = scatteredInterpolant(aero_synt(:,1),...        % CLad interpolation
                aero_synt(:,2),aero_synt(:,15) );
            obj.CMad = @(M,Re,alpha) CH3(M,Re)*alpha + CH4(M,Re);
            
            % dCM/dM interpolation
            CM1 = griddedInterpolant(aero_synt_M(:,1),...         
                aero_synt_M(:,2),'linear','nearest' );
            CM2 = griddedInterpolant(aero_synt_M(:,1),...         
                aero_synt_M(:,3),'linear','nearest' );
            obj.CMM = @(M,alpha) CM1(M)*alpha + CM2(M);
            % Control Derivatives
            
            D1 = scatteredInterpolant(aero_synt_C(:,1),...         % dCM/dDe at given alpha interpolation
                aero_synt_C(:,2),aero_synt_C(:,4) );
            D2 = scatteredInterpolant(aero_synt_C(:,1),...         % dCM/dDe at given alpha interpolation
                aero_synt_C(:,2),aero_synt_C(:,6) );
            
            obj.CLde = @interpCLde;
            obj.CMde = @interpCMde;
            
            % Polar
            obj.polar =@(M,Re,CL) obj.CD0(M,Re) + obj.K(M,Re)*( CL(:) - obj.CLcdm(M,Re) ).^2;
            catch ERR
                warning('Could not load Aerodynamic Data')
            end
            % Controllers Gains
            %obj.Kp(:,:,1) = Kp; obj.Kb(:,:,1) = Kb; obj.Ki(:,:,1) = Ki;
            try
                [obj.Kb,obj.Kp,obj.Ki] = obj.gain_assign(gain_file);
            catch
                warning('No gain file found')
                obj.Kp(:,:,1) = nan(2,4); obj.Kb(:,:,1) = nan(2,4); obj.Ki(:,:,1) = nan(2,4);
            end
            
            %% Auxiliary Interpolating Functions
            
            function CMde = interpCMde(M,Re,deltaE)
            %interpCMde: interpolates the dCM/dDE and caps the elevator 
            % deflection 
                if deltaE < aero_synt_C(:,7)
                    deltaE = aero_synt_C(:,7);
                elseif deltaE > aero_synt_C(:,8)
                    deltaE = aero_synt_C(:,8);
                end
                CMde = D2(M,Re)*deltaE;
            end
            
            function CLde = interpCLde(M,Re,deltaE)
            %interpCLde: interpolates the dCM/dDE and caps the elevator 
            % deflection 
                if deltaE < aero_synt_C(:,7)
                    deltaE = aero_synt_C(:,7);
                elseif deltaE > aero_synt_C(:,8)
                    deltaE = aero_synt_C(:,8);
                end
                CLde = D1(M,Re)*deltaE;
            end
            
            function CL = CLvsAoA(M,Re,alpha)
            %CLVSAOA: function that evaluates only the linear trait of
            % CL-alpha curve, capping the value at CLmax.
                CL = nan(length(alpha),1);
               for i = 1:length(alpha)
                   CL(i) = obj.CLa(M,Re)*alpha(i) + obj.CL0(M,Re);
                   CL_max = obj.CLmax(M,Re);
                   if CL(i) > CL_max
                       CL(i) = CL_max;
                   end
               end
            end

        end
        
        function [obj,data_name,gain_name,inertia,propeller] = read_input(obj,dataFileName)
            %READ_INPUT: Reads aircraft data from the txt file
            %   Detailed explanation goes here
            function test_block(f_id,test)
                temp = fgetl(f_id);
                if ~strcmp(temp,test)
                    error( strcat('Expected',test,'fields') );
                end
            end
            
            [f_id,err_txt] = fopen(dataFileName,'r');                             % Read Input File
            if f_id == -1
                disp( strcat('Error Opening ',dataFileName,'. ',err_txt) );
            else
                try
                disp('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%')
                lin = fgetl(f_id); strtok(lin,{'%'}) % Skips firt line
                lin = fgetl(f_id); lin = strtok(lin,sprintf(' \t%')); obj.Name = lin; % Name
                lin = fgetl(f_id); lin = strtok(lin,sprintf(' \t%')); data_name  = lin;
                lin = fgetl(f_id); lin = strtok(lin,sprintf(' \t%')); gain_name  = lin;
                lin = fgetl(f_id); lin = strtok(lin,sprintf(' \t%')); inertia  = lin;
                lin = fgetl(f_id); lin = strtok(lin,sprintf(' \t%')); propeller  = lin;
                % Masses
                test_block(f_id,'MASSES');
                lin = fscanf(f_id,'%f '); obj.MTOM = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.MTO = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.MLND = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.MZF = lin; fgetl(f_id);
                % Wing
                test_block(f_id,'GEOMETRY');

                test_block(f_id,'WING');
                lin = fscanf(f_id,'%f '); obj.Sw = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.bw = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.cref = lin; fgetl(f_id);
                % Thrust
                test_block(f_id,'ENGINE');
                lin = fscanf(f_id,'%f '); obj.Neng = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.RPM = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.Dprop = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.Pmax = lin*1000 ; fgetl(f_id);
                obj.EnPs = nan(3,1);
                lin = fscanf(f_id,'%f '); obj.EnPs(1) = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.EnPs(2) = lin; fgetl(f_id);
                lin = fscanf(f_id,'%f '); obj.EnPs(3) = lin; fgetl(f_id);
                
                fclose(f_id);
                catch ERR
                    warning(['Failed Reading File Fields',ERR.message])
                   fclose(f_id);
                end
            end
        end
        
        function [Tout,P0,K0,Kv] = Thrust_Model(obj,h,V,deltaT,flg,Treq)
        %THRUST_MODEL: Function that evaluates the thrust at a given flight 
        % condition or checks if the required thrust is attainable at the 
        % given flight condition. It uses two models and it works only for 
        % turboprop.
        %   INPUT
        %   - h: altitude [m]
        %   - V: airspeed [m/s]
        %   - deltaT: admission rate [-] Must be between 0 and 1
        %   - flg: flag defining the method used 'simple' 'complx'
        %   - Treq: if passed, checks if it is attainable [N}
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            [T, a, P, rho] = atmosisa(h);
            q = 0.5*rho*V^2;
            J = V/(obj.Dprop*obj.RPM)*60; % Advance Ratio
            P0 = obj.Pmax*( 1+0.008*(V*3.6/100)^2 )*(rho/1.225)^obj.nEn; % Shaft Power [W]
            if deltaT > 1
                deltaT = 1;
            elseif deltaT < 0
                deltaT = 0;
            end
            switch flg
                case 'simple'
                    % Simple model based on CT = (K0 + Kv/V^3)*dT
                    if J < obj.aTS.bds(1) || J > obj.aTS.bds(2) % Checks if J is within limits of the model
                        Tout = nan;
                        warning('J outside bounds, use complx model')
                    else
                        K0 = obj.aTs(1)/(0.5*rho*obj.Sw)*obj.Pmax*(rho/1.225)^obj.nEn;
                        Kv = obj.aTs(2)/(0.5*rho*obj.Sw)*obj.Pmax*(rho/1.225)^obj.nEn;
                        Tout = q*obj.Sw*( K0+Kv/(V^3) )*deltaT;
                    end
                case 'complx'
                    K0 = nan; Kv = nan;
                    if ~(J > 0)
                        %TODO FINIREEEEEEEEEEEEEEEEEEEE
                    else
                        %P0 = ( 1+0.008*(V*3.6/100)^2 )*(rho/1.225)^obj.nEn;
                        Tout = P0*deltaT/V*polyval(obj.aTC.cfs,J);
                    end
                    
                    
            end
            if nargin == 6
               if Treq < Tout
                    Tout = Treq;
               end
            end
            
        end
        
        function T = Thrust_Law(obj,Treq,h,flg)
        %THRUST_LAW Function that models the thrust produced by the engine
        %   T = Thrust_Law(Treq,h): checks if the required thrust passed with Treq
        %       is actually available at the given altitude h. If that is the case,
        %       the function returns T, otherwise it returns the maximum available
        %       thrust at the given altitude
        %   T = Thrust_Law(Treq,h,flag): if flag is passed, Treq is the admission
        %       rate of the engine at the given altitude and teh funcion returns the
        %       thrust developed by the engine(s) for the given combination of
        %       admisison rate and altitude. 
        %           (i) ipt: the admission rate is taken from the one in input
        %          (ii) idl: engine is set to idle
        %         (iii) mxT: engine is set to max TO
        %          (iv) mxC: engine is set to max continous
        
        % TODO - FARE MODELLO MOTORE per ora i numeri sono temporanei
            Tmax = 12000; % N
            if nargin == 3
                T = Treq;
                if Treq > Tmax 
                    T = Tmax;
                elseif Treq < Tmax*0.5
                    T = Tmax*0.5; % Limits to idle
                end
            else
                if Treq > 1 || Treq < 1
                    error('Admission rate must be between [0,1]')
                end
                switch flg
                    case 'ipt' % Admission rate is given as input
                        T = Tmax*Treq;
                    case 'idl'
                        T = 0.5*Tmax; % IDLE FINIREEEE
                    case 'mxT'
                        % VEDERE in che modo implementare il motore, potranno essere
                        % anche sostituiti da Tmax(h)
                    case 'mxC'
            
                end
            end
        end

        function [CL,CD] = Aerodynamic_Mod(obj,flag,h,M,inp)
        %AERODYNAMIC_MOD Function that models the aerodynamic characteristics of
        %the aircraft
        %   L = Aerodynamic_Mod("t",h,inp): checks if the required CL 
        %       passed with inp is actually available at the given altitude h.
        %       If that is the case, the function returns T, otherwise it returns 
        %       the maximum available lift at the given altitude
        %       
        %       
        %   [L,D] = Aerodynamic_Mod("alpha",h,inp): calculates all teh aerodynamic
        %           data for a given combination of alpha and altitude
        
        % TODO - FARE MODELLO AERODINAMICO per ora i numeri sono temporanei
        
            Re = obj.ReCalc(h,M);       % Flight Reynolds Number
            
            %CLmax = 1.8; % TEMPORANEOOO
            % [M,Re,CD0,K,CL@min(Cd),CLa,CL0,CLmax,AoA@CLmax]
            switch flag
                case "t"
                    CLm = obj.CLmax(M,Re);                                      
                    CL = inp(:);
                    if any( abs(inp) > CLm ) % TEMP: ASSUMIAMO PER ORA CHE CLmax positivo e negativo siano uguali
                       CL( abs(inp) > CLm) = CLm.*CL( abs(inp) > CLm)...
                           ./abs( CL(abs(inp) > CLm) ) ;
                    end
                    
                    CD = obj.polar(M,Re,CL);
            end
        end
        
        function RE = ReCalc(obj,h,M)
            %RECALC: calculates Reynolds Numer at a given Mach and altitude.
            [T, a, ~, rho] = atmosisa(h);
            mu = 1.458e-6 * T^(3/2)/(T+110.4); % Sutherland Law used for retrocompatibility with older matlab versions
            V = M*a; RE = V*obj.cref*rho/mu;
        end
        
        function [Alon,Blon,C,D] = LinSystComp(obj,x0)
       %LINSYSCOMP: Function that builds the matrices for the complete 
       %linearised aircraft model
       %    INPUT
       %    - x0: state vector [u,v,w,p,q,r,x,y,z,psi,teta,phi,m]
       
           [T, a, P, rho] = atmosisa(-x0(9));
           M = norm(x0(1:3),2)/a;   
           Re = obj.ReCalc(-x0(9),M);
           q0 = 0.5*rho*x0(1)^2;
           K1 = q0*obj.Sw/x0(13); mu0 = 2*x0(13)/(rho*obj.Sw*obj.cref);
           CL = x0(13)*9.81/(q0*obj.Sw);    % Equilibrium CL
           
            % Derivatives
           dCLda = obj.CLa(M,Re);% Lift Curve slope
           dCDda = 2*obj.K(M,Re)*( CL - obj.CLdmin(M,Re) )*dCLda; % Parabolic polar slope
           dCMda = obj.CMa(M,Re); % CM slope
           dCMdad = obj.CMad(M,Re);
           dCLdDe = obj.CLde(M,Re);
           dCMdDe = obj.CMde(M,Re);
           dCMdM = obj.CMm(alpha);
           dCLdM = M/(1-M^2); % Prandtl Glauert
           dCLdq = obj.CLq(M);
           dCMdq = obj.CMq(M);
           
           Xu = -K1/x0(1)*(3*CD + CL*tan(x0(8)) + M*dCMdM ); % COnstant Power
           Xw = K1/x0(1) * (CL-dCDda);
           
           Zu = -K1/x0(1)*( 2*CL + M*dCLdM );
           Zw = -K1/x0(1)*( Cd+dCLda );
           Zwd = -0.5*dCLdad/mu0; 
           
           Mu = q0*obj.Sw*obj.cref/(obj.I(2,2)*x0(1))*...
               ( dCMdM+obj.zT/obj.cref*dCTdM );
           Mw = q0*obj.Sw*obj.cref/(obj.I(2,2)*x0(1))*dCMda;
           Mwd = rho*obj.Sw*obj.cref/(obj.I(2,2)*x0(1) )*dCMdad;
           Mq = rho*x0(1)*obj.Sw*obj.cref^2/obj.I(2,2)*dCMdq;
           K2 = Mwd/(1-Zwd);
           
           Zq = -x(1)*0.5/K2*dCLdq;
           
           Mde = q0*obj.Sw*obj.cmac/obj.I(2,2)*dCMdDe;
           Zde = K1*dCLdDe;
           Xdt = K1*(obj.CTfix + obj.Kv/( x0(1) )^2); % Constant Power
           Mdt = obj.zT/obj.cref*CT;
           
           
           Alon = [ Xu   , Xw         , 0                , -9.81*cos(x(8)); ...
               Zu, Zw ,Zq+xo(1), -9.81*sin(x(8));...
               Mu + K2*Zu, Mw + k2*Zw , Mq + K2*(Zq+x(8)), -K2*9.81*sin(x(8))
               0,0,1,0];
           
           Alon(2,:) = Alon(2,:)/(1-Zwd);
           
           Blon = [Xdt,Xde; Zdt,Zde; Mdt+K2*Zdt,Mde+K2*Zde;0,0];
           Blon(2,:) = Blon(2,:)/(1-Zwd);
            
        end
        
        function [A,B,C,u0] = LongLinSys(obj,x0,m)
        %LONGLINSYS: Builds the linearized reduced dynamic model 
        %around x0. The reduced model is the one based on the NAPE
        %equations.
        %   INPUT
        %   x0 - Vettore delle varibili di stato longitudinali nella cond. di rif.
        %       [Va,ga,h]
        %   m - Aircraft mass around condition
        %   OUTPUT
        %   A
        %   C - Output matrix, returns [VIAS;M;h;hdot] in imperial
        %       units: VIAS in kts, h in ft, hdot fpm
            
            g = 9.81; gm = 1.4;
            [T, a, p, rho] = atmosisa([0,x0(3)]);
            
            M = x0(1)/a(2); Re = obj.ReCalc(x0(3),M);
            CL = m*g*2/(rho(2)*obj.Sw*x0(1)^2); % Trim CL
            
            u0 = zeros(2,1); u0(1) = CL; 
            u0(2) = rho(2)*0.5*obj.Sw*...
                x0(1)^2*obj.polar(M,Re,CL);
            %u0 = u0*rho(2)*0.5*AC.Sw*x0(1)^2;
            
            A = zeros(3);
            A(1,1) = -rho(2)*x0(1)*obj.Sw*( obj.polar(M,Re,CL) )/m; % dfVa/dVa
            A(1,2) = -g*cos(x0(2)); % dfVa/dga
            A(2,1) = rho(2)*obj.Sw*CL/(2*m) + g/(x0(1)^2)*cos(x0(2)); % dfga/dVa
            A(2,2) = g/x0(1) * sin(x0(2)); % dfga/dga
            A(3,1) = sin(x0(2));% dfh/dVa
            A(3,2) = x0(1)*cos(x0(2));% dfh/dga
            
            B = zeros(3,2);
            B(1,1) = -rho(2)*x0(1)^2*obj.Sw*obj.K(M,Re)*(CL - obj.CLcdm(M,Re))/m; % dfVa/dCL
            B(1,2) = 1/m; % dfVa/dT
            B(2,1) = rho(2)*x0(1)*obj.Sw/(2*m); % dfGa/dCL
            
            C = zeros(4,3);
            M = x0(1)/a(2); MMS = (1+0.5*(gm-1)*M^2)^(1/(gm-1));
            C(1,1) = a(1)/a(2) * p(2)/p(1) * M*MMS*( p(2)/p(1)*( MMS^gm - 1 ) + 1 )^(-1/gm);
            C(1,1) = C(1,1)/ sqrt( 2/(gm-1)*( ( p(2)/p(1)*( MMS^gm - 1 ) + 1 )^(1-1/gm) -1 ) ); % dgVIAS/dVa
            C(1,1) = C(1,1)/0.51444; % VIAS in kts
            C(2,1) = 1/a(2); % dgM/dVa
            C(3,3) = 1/0.305;  % dgh/dh in feet
            C(4,2) = A(3,2)*60/0.305; % dghdot/dga fpm
            
        end
        
        function lam = CheckCont(obj,xtest,Kp,Ki,Kb)
        %CHECKCONT: Function that calculates the roots of the
        %characteristic equation for a given gain matrix on all conditions
        %given by xref

        Kg = [Kp+Kb;Ki]; lam = nan(length(xtest(:,1)),5); % Works only with 5 state variables
        for i = 1:length(xtest(:,1))
            [A,B,C,D] = obj.LongLinSys( xtest(i,1:3),xtest(i,4) );
            Ai = [A,B;zeros(2,5)]; Bi = [B,zeros(3,2);zeros(2,2),eye(2)];
            Ci = [C,zeros(4,2)];
            lam(i,:) = eig(Ai - Bi*Kg*Ci)';

        end

        end
        
        function rt = turnRadius(obj,V,phi)
        %TURNRADIUS: function that returns the turn radius for a given
        %speed and weight
            n = 1/cos(phi);     % Load Factor
            rt = V^2/(9.81*sqrt(n^2-1));
        end
        
        function Vout = body2NED(obj,Vi,flg,psi,teta,phi)
        %BODY2NED: function that expresses the vector Vi defined in the
        %body reference frame into the NED reference and vice-versa

            nps = length(psi); nt = length(teta); nph = length(phi);
            if nps > 1 && (nps ~= nt) && (nps ~= nph)
                error('The number of vectors passed must be equal to the number of coordinates, if more than one vector is passed')
            end
            Vout = nan(3,nps);
            for j = 1:nps
                ct = cos(teta(j)); st = sin(teta(j));
                cp = cos(phi(j));  sp = sin(phi(j));
                cps = cos(psi(j)); sps = sin(psi(j));

                M = [ct*cps,ct*sps,-st; ...
                    -cp*sps+sp*st*cps, cp*cps+sps*st*sp,sp*ct;...
                    sp*sps+cp*st*cps,-sp*cps++cp*st*sps,ct*cp];     % NED2Body
                if isequal(flg,'B2N')
                    M = M';
                end
                Vout(:,j) = M*Vi(:);
            end
        end

        function [Kb,Kp,Ki] = gain_assign(obj,name)
            load(name,'Kb','Kp','Ki');
            %Kb = GNS.Kb;
            % switch flg
            %     case 'CLcHd'
            %         obj.Kp(:,:,1) = Kp; obj.Kb(:,:,1) = Kb; obj.Ki(:,:,1) = Ki;
            %     case 'CLcV'
            %         obj.Kp(:,:,2) = Kp; obj.Kb(:,:,2) = Kb; obj.Ki(:,:,2) = Ki;
            %     case 'CLTcVh'
            %         obj.Kp(:,:,3) = Kp; obj.Kb(:,:,3) = Kb; obj.Ki(:,:,3) = Ki;
            % end
        end
    end
end

